twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        app_name: 'Handwerker'
    form_themes: ['form/form-theme.html.twig']
