api_login_check:
  path:
    en: /login_check
    de: /login_check_de

home:
  path:
    en: /
    de: /startseite
  controller: App\Infrastructure\Controller\HomeController:handleRequest
  methods: [get]
  defaults:
    template: home.html.twig

login:
  path:
    en: /login
    de: /einloggen
  controller: App\Infrastructure\Controller\LoginController:handleRequest
  methods: [get]

loginSuccess:
  path:
    en: /auth/success
    de: /auth/success
  controller: App\Infrastructure\Controller\HomeController:handleRequest
  methods: [get]

createUser:
    path:
      en: /user
      de: /benutzer
    controller: App\Infrastructure\Controller\RegisterUserController:handleRequest
    methods: [post]
    defaults:
      template: home.html.twig

createJob:
  path:
    en: /job
    de: /arbeit
  controller: App\Infrastructure\Controller\CreateJobController:handleRequest
  methods: [post]

updateJob:
  path:
    en: /job
    de: /arbeit
  controller: App\Infrastructure\Controller\UpdateJobController:handleRequest
  methods: [put]

getJob:
  path:
    en: /job/{uuid}
    de: /arbeit/{uuid}
  controller: App\Infrastructure\Controller\GetJobController:handleRequest
  methods: [get]
  requirements:
    uuid: !php/const App\Domain\ValueObject\Uuid::UUID_PATTERN

deleteJob:
  path:
    en: /job/{uuid}
    de: /arbeit/{uuid}
  controller: App\Infrastructure\Controller\DeleteJobController:handleRequest
  methods: [delete]
  requirements:
    uuid: !php/const App\Domain\ValueObject\Uuid::UUID_PATTERN
